name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      ApigeeOrg:
        type: choice
        description: select Org to deploy 
        options:
        - shell-nonprod
        - shell
      environment:
        type: choice
        description: select env to deploy 
        options:
          - dev
          - test
          - prod
        
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usage
        run: echo "Print profile - ${{github.event.inputs.environment}}"
       
