name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      ApigeeOrg:
        type: choice
        description: select Org to deploy 
        options:
        - shell-nonprod
        - shell
      environment:
        type: choice
        description: select env to deploy 
        options:
          - dev
          - test
          - prod
        
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    
    env:
      apigeeProfile: dev
      
    steps:
      - name: dev  profile 
        env:
           profile: ${{(github.event.inputs.environment == 'dev' && github.event.inputs.ApigeeOrg == 'shell-nonprod')}}
        run: |                
                if ${profile} == true; then
                  echo "flag=true" >> $GITHUB_ENV
                  echo "profile is set to dev"
                  for ((i = 0 ; i < 10 ; i++)); do
                  echo "dev  Profile"
                  done  
                else
                  echo "flag=false" >> $GITHUB_ENV
                  echo "profile is not set to dev"
                fi                
      
      - name: test Profile
        env:
           profile: ${{(github.event.inputs.environment == 'test' && github.event.inputs.ApigeeOrg == 'shell')}}
        run: |                
                if ${profile} == true; then
                  echo "flag=true" >> $GITHUB_ENV
                  echo "profile is set to test"
                  for ((i = 0 ; i < 10 ; i++)); do
                  echo "Test  Profile"
                  done  
                else
                  echo "flag=false" >> $GITHUB_ENV
                  echo "profile is not set to test"
                fi              
        
      - name: prod Profile
        env:
           profile: ${{(github.event.inputs.environment == 'prod' && github.event.inputs.ApigeeOrg == 'shell')}}

        run: |                
                if ${profile} == true; then
                  echo "flag=true" >> $GITHUB_ENV
                  echo "profile is set to prod"
                  for ((i = 0 ; i < 10 ; i++)); do
                  echo "Prod  Profile"
                  done  
                else
                  echo "flag=false" >> $GITHUB_ENV
                  echo "profile is not set to Prod"
                fi 
