name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      ApigeeOrg:
        type: choice
        description: select Org to deploy 
        options:
        - shell-nonprod
        - shell
      environment:
        type: choice
        description: select env to deploy 
        options:
          - dev
          - test
          - prod
        
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    
    env:
      apigeeProfile: dev
      
    steps:
      - name: dev  profile 
           if:${{(github.event.inputs.environment == 'dev' && github.event.inputs.ApigeeOrg == 'shell-nonprod')}}
        run: |
                for ((i = 0 ; i < 10 ; i++)); do
                  echo "Dev Profile"
                done               
      
      - name: test Profile
           if:${{(github.event.inputs.environment == 'test' && github.event.inputs.ApigeeOrg == 'shell')}}
         
        run: |
                for ((i = 0 ; i < 10 ; i++)); do
                  echo "Test  Profile"
                done      
        
      - name: prod Profile
            if:${{(github.event.inputs.environment == 'prod' && github.event.inputs.ApigeeOrg == 'shell')}}
        run: |
                for ((i = 0 ; i < 10 ; i++)); do
                  echo "prod  Profile"
                done 
